//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceCompareWebAPIService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICECOMPARE
    {
        public int id { get; set; }
        public string airlinename { get; set; }
        public string airlineclass { get; set; }
        public Nullable<int> fare { get; set; }
    }
}
